import axios from 'axios';

const bearerToken = localStorage.getItem('accessToken');
export const bearer='Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJKdUZ2YVlEenppMFV4WnZhOVpxUDhvbEJSZUVyNVNKcUo0TU1xYUMtbDZJIn0.eyJleHAiOjE3MDIzOTg3ODcsImlhdCI6MTcwMjM2Mjc4NywianRpIjoiM2ZhOGQyMWEtMzg5Ni00Y2NmLTk5MDEtZmI5NWY4ZGU1N2E2IiwiaXNzIjoiaHR0cHM6Ly9zdGFnaW5nLmFwaS50cmlsbGl1bS5oZWFsdGgvcmVhbG1zL2NsaW5pYyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI4Y2RiNzdmOC02MzRjLTQxN2UtYjIzZS1iNzkzNDkzYzIzY2YiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJtZWRpY2FsLWNvZGluZyIsInNlc3Npb25fc3RhdGUiOiI4ZWViYWNlZC00OGY5LTRjMmQtYmY2My04YzYzYjAzZWRiMmQiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9zdGFnaW5nLmFwaS50cmlsbGl1bS5oZWFsdGgiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY2xpbmljIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkNPREVSX1BPUlRBTCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiI4ZWViYWNlZC00OGY5LTRjMmQtYmY2My04YzYzYjAzZWRiMmQiLCJjbGluaWNJZCI6MCwiaXNBZG1pbmlzdHJhdG9yQWNjZXNzIjpmYWxzZSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiVGVzdCBDb2RpbmciLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJjb2RpbmcxIiwiZ2l2ZW5fbmFtZSI6IlRlc3QiLCJmYW1pbHlfbmFtZSI6IkNvZGluZyIsInVzZXJJZCI6NjUxfQ.Eu3mt4okofntTR69xoi7j3bOoO3doWSD3BxQ1W3WtsnYyIHD6WudlIT8gYxnQy6p2i1Yve_HLqwroDHLWUBY9NdaZeoDvZOnSQEQw7RWr9cHsX4_MDo4gFahEg8UMHIHgZ8rnHTsDKpJcnF4-qWFjS4SysT8Z6kRsiTtIRHilUiJBPrHcYFiKnw7UqBFeBws14IA5OmpvOfbU3zFLFw5ffIRwhKB82BvgtKrVbC0GdSfj3Sa61WEUr_fWOAUiNnJPf1PgxL3_NpoARwSQfa9--aSr9t-dZeHrVJTx_VIRs8ZWzL8Id6RI59xBxgl-E3sfZsz4VuwerdGu52aN87UMA'
export default axios.create({
  baseURL: 'https://staging.api.trillium.health',
  headers: {
    'Content-type': 'application/json',
    Authorization: `Bearer ${bearerToken}`,
  },
});
